/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Edson
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        
            ColecaoConsultas col =new  ColecaoConsultas();
            
            initComponents();
       
        
        
        //initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        tela = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        consultas = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        qtdconsulta_pdata = new javax.swing.JMenuItem();
        qtdconsulta_pmedico = new javax.swing.JMenuItem();
        listarconsulta_ppaciente = new javax.swing.JMenuItem();
        medico = new javax.swing.JMenu();
        pesquisarmedico_crm = new javax.swing.JMenuItem();
        removermedico_crm = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        pesquisarmedico_pnome = new javax.swing.JMenuItem();
        paciente = new javax.swing.JMenu();
        adcpaciente = new javax.swing.JMenuItem();
        removerpaciente_doc = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");
        jPopupMenu1.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jPopupMenu1.add(jMenuItem7);

        jMenuItem8.setText("jMenuItem8");
        jPopupMenu1.add(jMenuItem8);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        consultas.setText("Consultas");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/imagens/application_side_boxes.png"))); // NOI18N
        jMenuItem4.setText("Adicionar Nova Consulta");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        consultas.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/imagens/add.png"))); // NOI18N
        jMenuItem5.setText("Listar Consultas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        consultas.add(jMenuItem5);

        qtdconsulta_pdata.setText("Quantidade de Consultas por Data");
        qtdconsulta_pdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdconsulta_pdataActionPerformed(evt);
            }
        });
        consultas.add(qtdconsulta_pdata);

        qtdconsulta_pmedico.setText("Quantidade de Consultas por Medico");
        consultas.add(qtdconsulta_pmedico);

        listarconsulta_ppaciente.setText("Listar Consulta por Paciente");
        consultas.add(listarconsulta_ppaciente);

        jMenuBar1.add(consultas);

        medico.setText("Medico");

        pesquisarmedico_crm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/imagens/add.png"))); // NOI18N
        pesquisarmedico_crm.setText("Adicionar Medico");
        pesquisarmedico_crm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarmedico_crmActionPerformed(evt);
            }
        });
        medico.add(pesquisarmedico_crm);

        removermedico_crm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/imagens/application_cascade.png"))); // NOI18N
        removermedico_crm.setText("Remover Medico por CRM");
        medico.add(removermedico_crm);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkginterface/imagens/application_double.png"))); // NOI18N
        jMenuItem3.setText("Pesquisar Medico por CRM");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        medico.add(jMenuItem3);

        pesquisarmedico_pnome.setText("Pesquisar Medico por parte do Nome");
        medico.add(pesquisarmedico_pnome);

        jMenuBar1.add(medico);

        paciente.setText("Pacientes");

        adcpaciente.setText("Adicionar Paciente");
        adcpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adcpacienteActionPerformed(evt);
            }
        });
        paciente.add(adcpaciente);

        removerpaciente_doc.setText("Remover paciente por Documento");
        paciente.add(removerpaciente_doc);

        jMenuItem9.setText("Pesquisar Paciente por Documento");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        paciente.add(jMenuItem9);

        jMenuItem10.setText("Quantidade de pacientes por sexo");
        paciente.add(jMenuItem10);

        jMenuItem11.setText("Listar Pacientes por endereco");
        paciente.add(jMenuItem11);

        jMenuItem12.setText("Listar Pacientes com mais de 60 anos");
        paciente.add(jMenuItem12);

        jMenuBar1.add(paciente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisarmedico_crmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarmedico_crmActionPerformed
         Adicionarmedico user=new Adicionarmedico();
       tela.add(user);
         user.setVisible(true);
    }//GEN-LAST:event_pesquisarmedico_crmActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        AdicionarConsultas user=new AdicionarConsultas();
        tela.add(user);
        user.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
       if (evt.isPopupTrigger()){
           jPopupMenu1.show(this, evt.getX(), evt.getY());
       }
    }//GEN-LAST:event_formMouseReleased

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void adcpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adcpacienteActionPerformed
       AdicionarPaciente user=new AdicionarPaciente();
        tela.add(user);
        user.setVisible(true);
    }//GEN-LAST:event_adcpacienteActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void qtdconsulta_pdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdconsulta_pdataActionPerformed
       
    }//GEN-LAST:event_qtdconsulta_pdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adcpaciente;
    private javax.swing.JMenu consultas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem listarconsulta_ppaciente;
    private javax.swing.JMenu medico;
    private javax.swing.JMenu paciente;
    private javax.swing.JMenuItem pesquisarmedico_crm;
    private javax.swing.JMenuItem pesquisarmedico_pnome;
    private javax.swing.JMenuItem qtdconsulta_pdata;
    private javax.swing.JMenuItem qtdconsulta_pmedico;
    private javax.swing.JMenuItem removermedico_crm;
    private javax.swing.JMenuItem removerpaciente_doc;
    private javax.swing.JDesktopPane tela;
    // End of variables declaration//GEN-END:variables
}

